"""
To access computation, we store all the index and text of queries and their corresponding relevant and nonrelevant 
documents into json files beforehand. All json files generated by this python file are related with Clueweb09 and 
can be found under Results/clueweb09/fold_1/rank_bert.

Besides, this file also present pca figures of frequently appeared adversarial tokens from local ranking attack 
for both datasets that was shown in Figure 6 in the short paper.
"""
from matplotlib.lines import Line2D
from transformers import BertTokenizer
from brittle.ranklist import Rerank, device
from models.bert_model import BertRanker
from Datasets import dataIterBase, dataIterBert, trec, trecdl
import numpy as np
import argparse
from tqdm import tqdm
import csv
from pathlib import Path
from typing import Dict, Any
import json
from pytorch_lightning import seed_everything
import torch
import matplotlib.pylab as plt
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler


bert_type = 'bert-base-uncased'
project_dir = Path(__file__).parent.absolute()
bert_cache = project_dir / 'pretrained/bert/'
glove_cache = project_dir / 'Datasets/pkl/glove_vocab.pkl'
datasets = ['clueweb09', 'msmarco_p']

csv.field_size_limit(100000000)


def init_rerank(dataset: str = 'clueweb09', reranker_type: str = 'bert', model_fold: str = 'fold_1'):
    queries = {}
    if dataset in datasets:
        if dataset == 'msmarco_p':
            data_dir = project_dir / f"Datasets/src/{dataset}"
            documents_file = data_dir / 'top_dev.tsv'
            top_file = data_dir / 'top_dev.tsv'
            queries_file = data_dir / 'top_dev.tsv'
            index_dir = str(data_dir / 'indexes' / f"{dataset}_indexes")
            queries = trecdl.get_queries(queries_file)

        else:
            data_dir = project_dir / f"Datasets/src/{dataset}"
            documents_file = data_dir / 'documents.tsv'
            top_file = data_dir / 'top.tsv'
            queries_file = data_dir / 'queries.tsv'
            index_dir = str(data_dir / 'indexes' / f"{dataset}_indexes")
            queries = trec.get_queries(queries_file)

        kwargs = {'data_file': None, 'train_file': None, 'val_file': None, 'test_file': None,
                  'training_mode': None, 'rr_k': None, 'num_workers': None, 'bert_type': bert_type, 'bert_cache': bert_cache, 'freeze_bert': False}

        if reranker_type == 'bert':
            model_dir = project_dir / \
                f'trained/pairwise/{model_fold}/{reranker_type}/lightning_logs/version_0/checkpoints/'
            checkpoint = str(list(model_dir.glob('*.ckpt'))[0])
            model = BertRanker.load_from_checkpoint(
                checkpoint, **kwargs).to(device).eval()

            InferenceDataset = dataIterBert.InferenceDataset(
                documents_file, top_file, bert_type, bert_cache, DATA=dataset, device=device)
            dataIterate = dataIterBert

        kwargs = {'dataset': dataset, 'RankModel': model, 'InferenceDataset': InferenceDataset,
                  'dataIterate': dataIterate, 'queries': queries, 'index_dir': index_dir}

        Reranker = Rerank(kwargs)
        return Reranker
    else:
        raise ValueError('Initial Reranker fails!')


def get_rank(hyparams: Dict[str, Any]):
    """ Get relevance scores and ranks of all pre-retrieved documents for 40 testset queries in Clueweb09."""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    predictions = []
    ranks = []
    for q_id in tqdm(hyparams['q_ids'], desc='Generating ranking list for each query:'):
        Reranker._init_query(q_id, rank_scores=True)
        predictions.append(Reranker.InferenceDataset.prediction.tolist())
        ranks.append(Reranker.InferenceDataset.rank.tolist())
    save_dir1 = hyparams['exp_fold'] / \
        f"rank_{hyparams['Rerank_model']}" / \
        'query_rank' / f"predictions.json"
    save_dir2 = hyparams['exp_fold'] / \
        f"rank_{hyparams['Rerank_model']}" / \
        'query_rank' / f"ranks.json"
    with open(save_dir1, 'w')as f:
        json.dump(predictions, f)
    with open(save_dir2, 'w')as f:
        json.dump(ranks, f)


def get_rank_200(hyparams: Dict[str, Any]):
    """Get relevance scores and ranks of all pre-retrieved documents for all 200 queries in Clueweb09"""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    pre_list = []
    rank_list = []
    q_id = [str(i) for i in range(1, 201)]
    for q_id in tqdm(q_id, desc='Generating ranking list for 200 query:'):
        Reranker._init_query(q_id, rank_scores=True)
        pre_list.append(Reranker.InferenceDataset.prediction.tolist())
        rank_list.append(Reranker.InferenceDataset.rank.tolist())
    save_dir1 = hyparams['exp_fold'] / \
        f"rank_{hyparams['Rerank_model']}" / '200_query'/'200_prediction.json'
    save_dir2 = hyparams['exp_fold'] / \
        f"rank_{hyparams['Rerank_model']}" / '200_query'/'200_rank.json'
    with open(save_dir1, 'w')as f:
        json.dump(pre_list, f)
    with open(save_dir2, 'w')as f:
        json.dump(rank_list, f)


def get_topdoc(hyparams: Dict[str, Any]):
    """Get the top-1 ranked document index for each query id in Clueweb09 testset. """
    batch_ids = []
    model_type = hyparams['Rerank_model']
    file = hyparams['exp_fold'] / \
        f'rank_{model_type}' / 'query_rank' / 'ranks.json'
    with open(file, 'r')as f:
        ranks = json.load(f)
    for index, q_id in enumerate(hyparams['q_ids']):
        batch_ids.append([q_id, ranks[index][0]])

    final = hyparams['exp_fold'] / f'rank_{model_type}' / 'id_pair.json'
    with open(final, 'w')as f:
        json.dump(batch_ids, f)


def get_topdoc_200(hyparams: Dict[str, Any]):
    """Get the top-1 ranked document index for each query id in the whole Clueweb09. """
    batch_ids = []
    model_type = hyparams['Rerank_model']
    file_path = hyparams['exp_fold'] / \
        f'rank_{model_type}' / '200_query' / '200_rank.json'
    with open(file_path, 'r')as f:
        rank = json.load(f)

    for i, q_id in enumerate(range(1, 201)):
        q_id = str(q_id)
        batch_ids.append([q_id, rank[i][0]])
    pair_path = hyparams['exp_fold'] / \
        f'rank_{model_type}' / '200_query' / 'id_pair.json'
    with open(pair_path, 'w')as f:
        json.dump(batch_ids, f)


def get_batch(hyparams: Dict[str, Any]):
    """Get query text and top-ranked document text pair for Clueweb09 testset."""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    working_path = project_dir / \
        f"Results/{hyparams['dataset']}/{hyparams['FOLD_NAME']}/rank_{hyparams['Rerank_model']}"
    batch_ids_path = working_path / 'id_pair.json'
    with open(batch_ids_path, 'r')as f:
        batch_ids = json.load(f)

    queries, batch_docs = [], []
    for index, q_id in enumerate(hyparams['q_ids']):
        queries.append(Reranker.queries[q_id])
        Reranker.InferenceDataset.__init_q_docs__(q_id, Reranker.queries[q_id])
        top_docs = Reranker.InferenceDataset.top_docs

        doc_index = batch_ids[index][1]
        batch_docs.append(top_docs[doc_index])
    out_path = working_path / 'batch_topdoc.json'
    with open(out_path, 'w')as f:
        json.dump({'queries': queries, 'batch_docs': batch_docs}, f)


def get_batch_200(hyparams: Dict[str, Any]):
    """Get query text and top-ranked document text pair for the whole Clueweb09."""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    working_path = project_dir / \
        f"Results/{hyparams['dataset']}/{hyparams['FOLD_NAME']}/rank_{hyparams['Rerank_model']}"
    batch_ids_path = working_path / '200_query' / 'id_pair.json'
    with open(batch_ids_path, 'r')as f:
        id_pairs = json.load(f)

    queries, batch_docs = [], []
    for index, q_id in enumerate(range(1, 201)):
        q_id = str(q_id)
        queries.append(Reranker.queries[q_id])
        _, top_docs = dataIterBase.read_top_docs(
            q_id, Reranker.InferenceDataset.documents_file, Reranker.InferenceDataset.top_file)
        doc_index = id_pairs[index][1]
        batch_docs.append(top_docs[doc_index])
    out_path = working_path / '200_query' / 'batch_topdoc.json'
    with open(out_path, 'w')as f:
        json.dump({'queries': queries, 'batch_docs': batch_docs}, f)


def get_lastdoc(hyparams: Dict[str, Any]):
    """Get the last_ranked document index for each query id in Clueweb09 testset. """
    batch_ids_last = []
    model_type = hyparams['Rerank_model']
    file = hyparams['exp_fold'] / \
        f'rank_{model_type}' / 'query_rank' / 'ranks.json'
    with open(file, 'r')as f:
        ranks = json.load(f)
    for index, q_id in enumerate(hyparams['q_ids']):
        batch_ids_last.append([q_id, ranks[index][-1]])

    final = hyparams['exp_fold'] / f'rank_{model_type}' / 'id_pair_lastdoc.json'
    with open(final, 'w')as f:
        json.dump(batch_ids_last, f)


def get_lastdoc_200(hyparams: Dict[str, Any]):
    """Get the last_ranked document index for each query id in the whole Clueweb09."""
    batch_ids_last = []
    model_type = hyparams['Rerank_model']
    file = hyparams['exp_fold'] / \
        f'rank_{model_type}' / '200_query' / '200_rank.json'
    with open(file, 'r')as f:
        rank = json.load(f)

    for i, q_id in enumerate(range(1, 201)):
        q_id = str(q_id)
        batch_ids_last.append([q_id, rank[i][-1]])
    pair_path = hyparams['exp_fold'] / \
        f'rank_{model_type}' / '200_query' / 'id_pair_lastdoc.json'
    with open(pair_path, 'w')as f:
        json.dump(batch_ids_last, f)


def get_batch_lastdoc(hyparams: Dict[str, Any]):
    """Get query text and last-ranked document text pair for Clueweb09 testset."""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    working_path = project_dir / \
        f"Results/{hyparams['dataset']}/{hyparams['FOLD_NAME']}/rank_{hyparams['Rerank_model']}"
    batch_ids_path = working_path / 'id_pair_lastdoc.json'
    with open(batch_ids_path, 'r')as f:
        batch_ids = json.load(f)

    queries, batch_docs = [], []
    for index, q_id in enumerate(hyparams['q_ids']):
        queries.append(Reranker.queries[q_id])
        """
        _, top_docs = dataIterBase.read_top_docs(
            q_id, Reranker.InferenceDataset.documents_file, Reranker.InferenceDataset.top_file)
        """
        Reranker.InferenceDataset.__init_q_docs__(q_id, Reranker.queries[q_id])
        top_docs = Reranker.InferenceDataset.top_docs

        doc_index = batch_ids[index][1]
        batch_docs.append(top_docs[doc_index])
    
    out_path = working_path / 'batch_lastdoc.json'
    with open(out_path, 'w')as f:
        json.dump({'queries': queries, 'batch_docs': batch_docs}, f)


def get_batch_lastdoc_200(hyparams: Dict[str, Any]):
    """Get query text and last-ranked document text pair for the whole Clueweb09."""
    Reranker = init_rerank(
        hyparams['dataset'], hyparams['Rerank_model'], hyparams['FOLD_NAME'])
    working_path = project_dir / \
        f"Results/{hyparams['dataset']}/{hyparams['FOLD_NAME']}/rank_{hyparams['Rerank_model']}/200_query"
    batch_ids_path = working_path / 'id_pair_lastdoc.json'
    with open(batch_ids_path, 'r')as f:
        batch_ids = json.load(f)

    queries, batch_docs = [], []
    for index, q_id in enumerate(range(1, 201)):
        q_id = str(q_id)
        queries.append(Reranker.queries[q_id])
        _, top_docs = dataIterBase.read_top_docs(
            q_id, Reranker.InferenceDataset.documents_file, Reranker.InferenceDataset.top_file)
        doc_index = batch_ids[index][1]
        batch_docs.append(top_docs[doc_index])
    out_path = working_path / 'batch_lastdoc.json'
    with open(out_path, 'w')as f:
        json.dump({'queries': queries, 'batch_docs': batch_docs}, f)


project_dir = Path(__file__).parent.absolute()
data_dir = project_dir / 'Datasets' / 'src' / 'clueweb09'
documents_file = data_dir / 'documents.tsv'
top_file = data_dir / 'top.tsv'
queries_file = data_dir / 'queries.tsv'

batch_ids_path = project_dir / 'Results' / 'clueweb09' / \
    'fold_1' / 'rank_bert' / 'id_pair.json'

result_path = project_dir / 'Results' / 'clueweb09' / \
    'fold_1' / 'rank_bert'
plot_path = project_dir / 'Results/paper_plot'

def _get_embedding_weight():
    rerank_model = init_rerank('clueweb09', 'bert', 'fold_1')
    for module in rerank_model.model.bert.modules():
        if isinstance(module, torch.nn.Embedding):
            # Bert has 5 embedding layers, only add a hook to wordpiece embeddings
            # BertModel.embeddingsword_embeddings.weight.shape == (30522,768)
            if module.weight.shape[0] == 30522:
                return module.weight.detach().cpu().numpy()


def pca_bias_tokens():
    embedding_weight = _get_embedding_weight()
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    # pca label: 0: clueweb09, 1: TREC-DL, 2: both
    # nature related tokens
    nature_tokens = ["hurricane", "hurricanes", "tornadoes", "tornado", "earthquakes",
                     "warming", "lightning", "prairie", "deserts", "precipitation", "darkening", "thunder"]
    nature_label = np.array([2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0])
    nature_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in nature_tokens]
    nature_vectors = np.concatenate([embedding_weight[id]
                                     for id in nature_token_ids])
    nature_length = len(nature_tokens)

    # religion related tokens
    religion_tokens = ["hinduism", "muslims", "baptist", 'unitarian', 'judaism',
                       "atheist", "celestial", "quran", "islam", "preach", "mormon", "preaching", 'catholicism', 'preached', 'christianity', 'jesus', 'archangel', 'evangelist', 'buddhism', 'sermons', 'psalms']
    religion_label = np.array(
        [2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 1, 1, 1, 1, 1])
    religion_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in religion_tokens]
    religion_vectors = np.concatenate([embedding_weight[id]
                                       for id in religion_token_ids])
    religion_length = len(religion_tokens)

    # ethnic tokens
    ethnic_tokens = ['viking', 'cherokee',
                     'latino', 'indians', 'seminole', 'negro', 'mexican', 'latin', 'italianate', 'arabic', 'haitian']
    ethnic_label = np.array([0, 2, 2, 0, 0, 0, 1, 1, 2, 1, 1])
    ethnic_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in ethnic_tokens]
    ethnic_vectors = np.concatenate([embedding_weight[id]
                                     for id in ethnic_token_ids])
    ethnic_length = len(ethnic_tokens)

    # medical tokens
    medical_tokens = ['antibiotics', 'ethanol', 'testosterone', 'cardiac',
                      'biotechnology', 'alexia', 'bacterial', 'diabetes',
                      'obesity', 'infection', 'malaria', 'dentistry',
                      'vitamin', 'chloride', 'surgeons', 'pregnancy',
                      'cholera', 'arthritis', 'nurses', 'hormones',
                      'neuroscience', 'diseases', 'autism', 'surgical',
                      'influenza', 'tuberculosis', 'dentist', 'tumors',
                      'inflammation']
    medical_label = np.array([2, 2, 2, 0,
                              2, 2, 2, 2,
                              0, 0, 1, 1,
                              1, 1, 1, 1,
                              1, 1, 1, 1,
                              1, 1, 1, 1,
                              1, 1, 1, 1,
                              1])
    medical_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in medical_tokens]

    medical_vectors = np.concatenate(
        [embedding_weight[id] for id in medical_token_ids])
    medical_length = len(medical_tokens)

    # get pca in 2D:
    random_state = 1
    pca = make_pipeline(StandardScaler(), PCA(
        n_components=2, random_state=random_state))
    X = np.concatenate((nature_vectors, religion_vectors,
                       ethnic_vectors, medical_vectors), axis=0)

    print(nature_vectors.shape,  religion_vectors.shape,
          ethnic_vectors.shape, medical_vectors.shape)
    pca.fit(X)
    X_pca = pca.transform(X)

    print(nature_length, religion_length,
          ethnic_length, medical_length, len(X_pca))

    # plot 4 categories
    plt.figure(figsize=(8, 6))
    colors = ['#F1D77E', '#B1CE46', '#5F97D2'] 
    for color, i, label in zip(colors, [0, 1, 2], ['ClueWeb09', 'TREC-DL', 'both']):
        X_nature = X_pca[:nature_length]
        plt.scatter(X_nature[nature_label == i, 0],
                    X_nature[nature_label == i, 1],
                    color=color,
                    marker='o'
                    )  
        X_religion = X_pca[nature_length:nature_length+religion_length]
        plt.scatter(X_religion[religion_label == i, 0],
                    X_religion[religion_label == i, 1],
                    color=color,
                    marker='<')
        X_ethnic = X_pca[nature_length +
                         religion_length:nature_length+religion_length+ethnic_length]
        plt.scatter(X_ethnic[ethnic_label == i, 0],
                    X_ethnic[ethnic_label == i, 1],
                    color=color,
                    marker='*')
        X_medical = X_pca[nature_length+religion_length+ethnic_length:]
        plt.scatter(X_medical[medical_label == i, 0],
                    X_medical[medical_label == i, 1],
                    color=color,
                    marker='D')
        # legend
        from matplotlib.patches import Patch
        legend_elements = [Patch(facecolor='#F1D77E', label='ClueWeb09'),
                           Patch(facecolor='#B1CE46',
                                 label='TREC-DL'),
                           Patch(facecolor='#5F97D2', label='both'),
                           Line2D([0], [0], color='w', markerfacecolor='black', markersize=10,
                                  marker='o', label='nature-related'),
                           Line2D([0], [0], color='w', marker='<', markerfacecolor='black', markersize=10,
                                  label='religion-related'),
                           Line2D([0], [0], color='w', markerfacecolor='black', markersize=15,
                                  marker='*', label='ethnicity-related'),
                           Line2D([0], [0], color='w', marker='D', markerfacecolor='black', markersize=8, label='medicine-related'), ]
        plt.legend(handles=legend_elements, fontsize=12)
        plt.xlabel('the first principal component', fontsize=16)
        plt.ylabel('the second principal component', fontsize=16)
        plt.savefig(plot_path/'pca_bias.eps',
                    format='eps', bbox_inches='tight')
        plt.savefig(plot_path/'pca_bias.png', bbox_inches='tight')


def pca_bias_tokens_inplace():
    embedding_weight = _get_embedding_weight()
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    nature_tokens = ["hurricane", "hurricanes", "tornadoes", "tornado", "earthquakes",
                     "warming", "lightning", "deserts", "precipitation",
                     "darkening", "thunder",
                     'meteorological', 'typhoon', 'storms', 'noah', 'exodus',
                     'drought', 'sunrise', 'rainfall']
    nature_label = np.array([2, 2, 2, 2, 2,
                            1, 0, 1, 2,
                             2, 2,
                             2, 1, 1, 1, 1,
                             1, 0, 0])
    nature_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in nature_tokens]
    nature_vectors = np.concatenate([embedding_weight[id]
                                     for id in nature_token_ids])
    nature_length = len(nature_tokens)

    # religion related tokens
    religion_tokens = ["hinduism", "muslims", "baptist", 'judaism',
                       "quran", "islam", "preach",
                       "mormon", "preaching", 'christianity',
                       'sermons', 'psalms',
                       'biblical', 'bible', 'satan', 'archangel', 'bless',
                       'gospel', 'synagogue', 'religious', 'parish']
    religion_label = np.array([
        2, 2, 2, 1,
        2, 0, 0,
        1, 1, 1,
        2, 1,
        1, 1, 1, 2, 1,
        0, 0, 0, 0])
    religion_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in religion_tokens]
    religion_vectors = np.concatenate([embedding_weight[id]
                                       for id in religion_token_ids])
    religion_length = len(religion_tokens)

    # ethnic tokens
    ethnic_tokens = ['viking', 'cherokee', 'latino', 'seminole',
                     'negro', 'mexican', 'latin', 'haitian',
                     'hispanic', 'texans', 'romans', 'hellenistic', 'americana',
                     'hawaiian', 'coptic', 'greek', 'ghanaian', 'afrikaans',
                     'nigerian', 'egyptian']
    ethnic_label = np.array([1, 2, 2, 2,
                             2, 1, 2, 0,
                             2, 2, 1, 1, 1,
                             2, 2, 1, 0, 0,
                             0, 0])
    ethnic_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in ethnic_tokens]
    ethnic_vectors = np.concatenate([embedding_weight[id]
                                     for id in ethnic_token_ids])
    ethnic_length = len(ethnic_tokens)

    # medical tokens
    medical_tokens = ['antibiotics', 'testosterone', 'biotechnology',
                      'alexia', 'infection',
                      'malaria', 'vitamin', 'surgeons',
                      'pregnancy', 'arthritis', 'hormones',
                      'diseases', 'autism', 'surgical', 'influenza',
                      'tuberculosis', 'inflammation',
                      'congenital', 'abortion', 'thyroid', 'symptoms',
                      'anatomical', 'therapist', 'surgery', 'insulin', 'medical',
                      'blood', 'infirmary', 'prescription', 'protein', 'flu',
                      'medicare', 'med', 'murals', 'syndrome', 'pneumonia',
                      'epidemic']
    medical_label = np.array([2, 1, 1,
                             2, 2,
                             1, 1, 2,
                             1, 1, 1,
                             1, 1, 1, 2,
                             2, 1,
                             1, 2, 1, 1,
                             1, 1, 1, 1, 1,
                             1, 1, 1, 1, 1,
                             1, 1, 0, 0, 0,
                             0])
    medical_token_ids = [tokenizer.encode(
        token, add_special_tokens=False) for token in medical_tokens]

    medical_vectors = np.concatenate(
        [embedding_weight[id] for id in medical_token_ids])
    medical_length = len(medical_tokens)

    # get pca in 2D:
    random_state = 1
    pca = make_pipeline(StandardScaler(), PCA(
        n_components=2, random_state=random_state))
    X = np.concatenate((nature_vectors, religion_vectors,
                       ethnic_vectors, medical_vectors), axis=0)
    pca.fit(X)
    X_pca = pca.transform(X)

    # plot 4 categories
    plt.figure(figsize=(8, 6))

    colors = ['#F1D77E', '#B1CE46', '#5F97D2']  
    for color, i, label in zip(colors, [0, 1, 2], ['ClueWeb09', 'TREC-DL', 'both']):
        X_nature = X_pca[:nature_length]
        plt.scatter(X_nature[nature_label == i, 0],
                    X_nature[nature_label == i, 1],
                    color=color,
                    marker='o'
                    )  
        X_religion = X_pca[nature_length:nature_length+religion_length]
        plt.scatter(X_religion[religion_label == i, 0],
                    X_religion[religion_label == i, 1],
                    color=color,
                    marker='<')
        X_ethnic = X_pca[nature_length +
                         religion_length:nature_length+religion_length+ethnic_length]
        plt.scatter(X_ethnic[ethnic_label == i, 0],
                    X_ethnic[ethnic_label == i, 1],
                    color=color,
                    marker='*')
        X_medical = X_pca[nature_length+religion_length+ethnic_length:]
        plt.scatter(X_medical[medical_label == i, 0],
                    X_medical[medical_label == i, 1],
                    color=color,
                    marker='D')
        # legend
        from matplotlib.patches import Patch
        legend_elements = [Patch(facecolor='#F1D77E', label='ClueWeb09'),
                           Patch(facecolor='#B1CE46',
                                 label='TREC-DL'),
                           Patch(facecolor='#5F97D2', label='both'),
                           Line2D([0], [0], color='w', markerfacecolor='black', markersize=10,
                                  marker='o', label='nature-related'),
                           Line2D([0], [0], color='w', marker='<', markerfacecolor='black', markersize=10,
                                  label='religion-related'),
                           Line2D([0], [0], color='w', markerfacecolor='black', markersize=15,
                                  marker='*', label='ethnicity-related'),
                           Line2D([0], [0], color='w', marker='D', markerfacecolor='black', markersize=8, label='medicine-related'), ]
        plt.legend(handles=legend_elements, fontsize=12)
        plt.xlabel('the first principal component', fontsize=16)
        plt.ylabel('the second principal component', fontsize=16)
        plt.savefig(plot_path/'pca_bias_inplace.eps',
                    format='eps', bbox_inches='tight')
        plt.savefig(plot_path/'pca_bias_inplace.png', bbox_inches='tight')


if __name__ == '__main__':

    ap = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument('FOLD_NAME', type=str,
                    help='Name of the fold. e.g. fold_1')
    ap.add_argument('Rerank_model', type=str, default='bert',
                    help='Name of the rerank model, e.g. bert')
    ap.add_argument('--dataset', type=str, default='clueweb09',
                    help='Dataset:clueweb09/msmarco_p')
    ap.add_argument('--top_k_docs', type=int,
                    help='Consider top k docs in the rankinglist')  # necessary?
    ap.add_argument('--mode', type=str, help='rankinglist, or ...')
    args = ap.parse_args()

    # get q_id
    q_ids_dir = project_dir / 'Datasets/src' / args.dataset
    exp_fold = project_dir / 'Results' / args.dataset / args.FOLD_NAME
    if args.dataset == 'msmarco_p':
        q_id_file = q_ids_dir / 'queries_dev_978.txt'
    else:
        q_id_file = q_ids_dir / 'folds' / args.FOLD_NAME / 'test_ids.txt'
    with open(q_id_file, 'r')as f:
        q_ids = [l.strip() for l in f]

    args.q_ids = q_ids
    args.exp_fold = exp_fold

    random_seed = 123
    seed_everything(random_seed, workers=True)

    if args.mode == 'rank':
        get_rank(vars(args))
    elif args.mode == 'rank_200':
        get_rank_200(vars(args))
    elif args.mode == 'topdoc':
        get_topdoc(vars(args))
    elif args.mode == 'topdoc_200':
        get_topdoc_200(vars(args))
    elif args.mode == 'batch':
        get_batch(vars(args))
    elif args.mode == 'batch_200':
        get_batch_200(vars(args))
    elif args.mode == 'batch_lastdoc':
        get_batch_lastdoc(vars(args))
    elif args.mode == 'batch_lastdoc_200':
        get_batch_lastdoc_200(vars(args))
    elif args.mode == 'lastdoc':
        get_lastdoc(vars(args))
    elif args.mode == 'lastdoc_200':
        get_lastdoc_200(vars(args))
    elif args.mode == 'pca_bias':
        pca_bias_tokens()
    elif args.mode == 'pca_bias_inplace':
        pca_bias_tokens_inplace()
    else:
        raise ValueError(f"no such mode:{args.mode}")
